---
language: node_js
node_js:
  - "4"

sudo: false

branches:
  only:
  - master
  - dev

cache: yarn

before_install:
  - pip install --user awscli
  - npm config set spin false
  - npm install --global yarn
  - yarn global add bower

install:
  - yarn install --ignore-engines
  - bower install

script:
  - npm test
  - cd $TRAVIS_BUILD_DIR
  - chmod +x ./deploy.sh

deploy:
  - provider: script
    script: ./deploy.sh dist $S3_STAGING
    skip_cleanup: true
    on:
      branch: dev
  - proivider: script
    script: ./deploy.sh dist $S3_PRODUCTION
    skip_cleanup: true
    on:
      branch: master
