---
language: node_js
node_js:
  - '4'

# workaround from https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-348227535
sudo: required
addons:
  chrome: stable

branches:
  only:
    - master
    - dev

cache: yarn

before_install:
  - pip install --user awscli
  - npm config set spin false
  - npm install --global yarn@1.10.1
  - yarn global add bower@1.8.4

install:
  - yarn install --ignore-engines
  - bower install

before_script:
  - chmod +x .travis/test-and-build.sh

script: .travis/test-and-build.sh

before_deploy:
  - chmod +x .travis/deploy.sh

deploy:
  - provider: script
    script: .travis/deploy.sh dist $S3_STAGING $AWS_CLOUDFRONT_ID_STAGING
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: .travis/deploy.sh dist $S3_PRODUCTION $AWS_CLOUDFRONT_ID_PRODUCTION
    skip_cleanup: true
    on:
      branch: master
