---
language: node_js
node_js:
  - "4"

sudo: required

branches:
  only:
  - master
  - dev

cache: yarn

before_install:
  - pip install --user awscli
  - npm config set spin false
  - npm install --global yarn
  - yarn global add bower

install:
  - yarn install --ignore-engines
  - bower install

script:
  - npm test

after_success:
  - npm run build -- --environment=production

before_deploy:
  - chmod +x .travis/deploy.sh

deploy:
  - provider: script
    script: .travis/deploy.sh dist $S3_STAGING
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: .travis/deploy.sh dist $S3_PRODUCTION $AWS_CLOUDFRONT_ID_PRODUCTION
    skip_cleanup: true
    on:
      branch: master
