---
language: node_js
node_js:
  - "4"

sudo: false

# branches:
#   only:
#   - $BRANCH_PRODUCTION
#   - $BRANCH_STAGING

cache: yarn

before_install:
  - pip install --user awscli
  - npm config set spin false
  - npm install --global yarn
  - yarn global add bower
  - yarn add phantomjs-prebuilt

install:
  - yarn install --ignore-engines
  - bower install

script:
  - npm test

# deploy:
#   - provider: script
#     script: bash deploy.sh dist $S3_STAGING
#     on:
#       branch: $BRANCH_STAGING
#   - proivider: script
#     script: bash deploy.sh dist $S3_PRODUCTION
#     on:
#       branch: $BRANCH_PRODUCTION
